export type LegacyDomain =
  | "identity"
  | "students"
  | "attendance"
  | "assessment"
  | "fees"
  | "communications"
  | "operations";

export interface LegacyFeatureLink {
  id: string;
  domain: LegacyDomain;
  legacyLabel: string;
  legacyEntryPoint: string;
  legacyFunctions: string[];
  newModuleHint?: string;
  newTableHint?: string;
  status: "pending" | "compatible" | "bridge-required" | "live";
  notes?: string;
}

export const legacyFeatureMap: LegacyFeatureLink[] = [
  // ── Identity & Auth ──
  {
    id: "IDA-LOGIN-01",
    domain: "identity",
    legacyLabel: "Login form",
    legacyEntryPoint: "Login screen",
    legacyFunctions: ["window.login()", "window.authenticate()"],
    newModuleHint: "supabase.auth.signInWithPassword",
    newTableHint: "auth.users",
    status: "live",
  },
  {
    id: "IDA-ROLE-01",
    domain: "identity",
    legacyLabel: "Role guarding",
    legacyEntryPoint: "App initialization",
    legacyFunctions: ["window.userRole", "window.hasAccess()"],
    newModuleHint: "src/lib/module-access.ts",
    newTableHint: "module_roles",
    status: "live",
  },
  {
    id: "IDA-SESS-01",
    domain: "identity",
    legacyLabel: "Session handling",
    legacyEntryPoint: "Page load",
    legacyFunctions: ["window.session", "window.refreshSession()"],
    newModuleHint: "supabase.auth.getSession",
    status: "live",
  },
  {
    id: "IDA-MFA-01",
    domain: "identity",
    legacyLabel: "MFA verification",
    legacyEntryPoint: "Login flow",
    legacyFunctions: ["window.verifyMfa()"],
    newModuleHint: "supabase.auth.mfa",
    status: "live",
  },

  // ── Student Master Data ──
  {
    id: "STU-CRUD-01",
    domain: "students",
    legacyLabel: "Add Student",
    legacyEntryPoint: "Students > Add",
    legacyFunctions: ["window.saveStudent()", "addStudentSection"],
    newModuleHint: "core/students/service.ts → createStudent()",
    newTableHint: "students",
    status: "live",
  },
  {
    id: "STU-CRUD-02",
    domain: "students",
    legacyLabel: "Edit Student",
    legacyEntryPoint: "Students > List > Edit",
    legacyFunctions: ["window.editStudent()", "populateForm()"],
    newModuleHint: "core/students/service.ts → updateStudent()",
    newTableHint: "students",
    status: "live",
  },
  {
    id: "STU-CRUD-03",
    domain: "students",
    legacyLabel: "Delete Student",
    legacyEntryPoint: "Students > List > Delete",
    legacyFunctions: ["window.deleteStudent()", "confirmDelete()"],
    newModuleHint: "core/students/service.ts → deleteStudentPermanently()",
    newTableHint: "students",
    status: "live",
  },
  {
    id: "STU-LIST-01",
    domain: "students",
    legacyLabel: "Student Directory",
    legacyEntryPoint: "Students > List",
    legacyFunctions: ["window.renderStudentTable()", "registeredSection"],
    newModuleHint: "src/lib/student-records.ts → fetchStudentRegister()",
    newTableHint: "students",
    status: "live",
  },
  {
    id: "STU-IMPORT-01",
    domain: "students",
    legacyLabel: "Batch Import (UMIS)",
    legacyEntryPoint: "Import > Create Batch",
    legacyFunctions: ["window.importUMIS()", "importSection"],
    newModuleHint: "src/lib/import-engine/",
    newTableHint: "import_batches",
    status: "live",
  },
  {
    id: "STU-EXPORT-01",
    domain: "students",
    legacyLabel: "Export Students",
    legacyEntryPoint: "Students > Export",
    legacyFunctions: ["window.exportCSV()"],
    newModuleHint: "src/pages/Students.tsx (CSV export)",
    newTableHint: "students",
    status: "live",
  },
  {
    id: "STU-PROMOTE-01",
    domain: "students",
    legacyLabel: "Promotion Engine",
    legacyEntryPoint: "Students > Promote",
    legacyFunctions: ["window.promoteStudents()"],
    newModuleHint: "core/academics/promotion.ts → executePromotion()",
    newTableHint: "enrollments",
    status: "live",
  },
  {
    id: "STU-DEACT-01",
    domain: "students",
    legacyLabel: "Deactivate Student",
    legacyEntryPoint: "Students > Deactivate",
    legacyFunctions: ["window.deactivateStudent()"],
    newModuleHint: "core/students/service.ts → deactivateStudent()",
    newTableHint: "enrollments",
    status: "live",
  },

  // ── Attendance ──
  {
    id: "ATT-DAILY-01",
    domain: "attendance",
    legacyLabel: "Daily Attendance",
    legacyEntryPoint: "Attendance > Daily",
    legacyFunctions: ["window.markAttendance()", "attendanceClassSection"],
    newModuleHint: "core/attendance/service.ts → markAttendance()",
    newTableHint: "attendance",
    status: "live",
  },
  {
    id: "ATT-PERIOD-01",
    domain: "attendance",
    legacyLabel: "Period-wise Attendance",
    legacyEntryPoint: "Attendance > Period",
    legacyFunctions: ["window.markPeriodAttendance()"],
    newModuleHint: "core/attendance/service.ts → markAttendance(period)",
    newTableHint: "attendance",
    status: "live",
  },
  {
    id: "ATT-BULK-01",
    domain: "attendance",
    legacyLabel: "Bulk Upload",
    legacyEntryPoint: "Attendance > Import",
    legacyFunctions: ["window.bulkUploadAttendance()", "attendanceImport"],
    newModuleHint: "core/attendance/service.ts → bulkUploadAttendance()",
    newTableHint: "attendance",
    status: "live",
  },
  {
    id: "ATT-OVERRIDE-01",
    domain: "attendance",
    legacyLabel: "Manual Override",
    legacyEntryPoint: "Attendance > Override",
    legacyFunctions: ["window.overrideAttendance()"],
    newModuleHint: "core/attendance/service.ts → overrideAttendance()",
    newTableHint: "attendance",
    status: "live",
  },
  {
    id: "ATT-REPORT-01",
    domain: "attendance",
    legacyLabel: "Attendance Report",
    legacyEntryPoint: "Reports > Attendance",
    legacyFunctions: ["window.attendanceReport()"],
    newModuleHint: "src/lib/reports.ts",
    newTableHint: "attendance",
    status: "live",
  },

  // ── Assessment & Exams ──
  {
    id: "ASM-EXAM-01",
    domain: "assessment",
    legacyLabel: "Exam Schedule",
    legacyEntryPoint: "Exams > Schedule",
    legacyFunctions: ["window.createExam()", "examSection"],
    newModuleHint: "src/lib/exams.ts → getExamSchedules()",
    newTableHint: "exam_schedules",
    status: "live",
  },
  {
    id: "ASM-MARKS-01",
    domain: "assessment",
    legacyLabel: "Marks Entry",
    legacyEntryPoint: "Exams > Marks",
    legacyFunctions: ["window.enterMarks()", "marksEntry()"],
    newModuleHint: "src/lib/exams.ts → saveMarks()",
    newTableHint: "exam_marks",
    status: "live",
  },
  {
    id: "ASM-GRADE-01",
    domain: "assessment",
    legacyLabel: "Grading",
    legacyEntryPoint: "Exams > Grades",
    legacyFunctions: ["window.calculateGrade()"],
    newModuleHint: "src/lib/exams.ts → calculateGrade()",
    newTableHint: "grade_schemes",
    status: "live",
  },
  {
    id: "ASM-GPA-01",
    domain: "assessment",
    legacyLabel: "GPA Calculation",
    legacyEntryPoint: "Exams > GPA",
    legacyFunctions: ["window.calculateGPA()"],
    newModuleHint: "src/lib/exams.ts → calculateGPA()",
    newTableHint: "exam_marks",
    status: "live",
  },
  {
    id: "ASM-DIST-01",
    domain: "assessment",
    legacyLabel: "Grade Distribution",
    legacyEntryPoint: "Exams > Distribution",
    legacyFunctions: ["window.getGradeDistribution()"],
    newModuleHint: "src/lib/exams.ts → getGradeDistribution()",
    newTableHint: "exam_marks",
    status: "live",
  },
  {
    id: "ASM-PASS-01",
    domain: "assessment",
    legacyLabel: "Pass/Fail Stats",
    legacyEntryPoint: "Exams > Stats",
    legacyFunctions: ["window.getPassFailStats()"],
    newModuleHint: "src/lib/exams.ts → getPassFailStats()",
    newTableHint: "exam_marks",
    status: "live",
  },
  {
    id: "ASM-REMARK-01",
    domain: "assessment",
    legacyLabel: "Remark Templates",
    legacyEntryPoint: "Exams > Remarks",
    legacyFunctions: ["window.remarkTemplates"],
    newModuleHint: "core/academics/remarks.ts → getRemarkTemplates()",
    newTableHint: "remarks_templates",
    status: "live",
  },
  {
    id: "ASM-SUBJ-01",
    domain: "assessment",
    legacyLabel: "Subjective Scoring",
    legacyEntryPoint: "Exams > Observations",
    legacyFunctions: ["window.scoreObservation()"],
    newModuleHint: "core/scoring/subjectiveToStandard.ts → evaluateObservation()",
    newTableHint: "audit_log",
    status: "live",
  },

  // ── Fees & Finance ──
  {
    id: "FEE-PLAN-01",
    domain: "fees",
    legacyLabel: "Fee Structure",
    legacyEntryPoint: "Fees > Plans",
    legacyFunctions: ["window.getFeeStructures()"],
    newModuleHint: "src/lib/fees.ts → getFeeStructures()",
    newTableHint: "fee_structures",
    status: "live",
  },
  {
    id: "FEE-INV-01",
    domain: "fees",
    legacyLabel: "Invoice Generation",
    legacyEntryPoint: "Fees > Invoices",
    legacyFunctions: ["window.generateInvoice()"],
    newModuleHint: "src/lib/fees.ts → getInvoices()",
    newTableHint: "fee_invoices",
    status: "live",
  },
  {
    id: "FEE-PAY-01",
    domain: "fees",
    legacyLabel: "Payment Recording",
    legacyEntryPoint: "Fees > Payments",
    legacyFunctions: ["window.recordPayment()"],
    newModuleHint: "src/lib/fees.ts → recordPayment()",
    newTableHint: "fee_payments",
    status: "live",
  },
  {
    id: "FEE-CONC-01",
    domain: "fees",
    legacyLabel: "Concession",
    legacyEntryPoint: "Fees > Concession",
    legacyFunctions: ["window.applyConcession()"],
    newModuleHint: "src/lib/fees.ts → applyConcession()",
    newTableHint: "fee_concessions",
    status: "live",
  },
  {
    id: "FEE-DUE-01",
    domain: "fees",
    legacyLabel: "Defaulter Report",
    legacyEntryPoint: "Fees > Defaulters",
    legacyFunctions: ["window.getDefaulters()"],
    newModuleHint: "src/lib/fees.ts → getDefaulters()",
    newTableHint: "fee_invoices",
    status: "live",
  },
  {
    id: "FEE-REM-01",
    domain: "fees",
    legacyLabel: "Payment Reminders",
    legacyEntryPoint: "Fees > Reminders",
    legacyFunctions: ["window.sendReminders()"],
    newModuleHint: "src/lib/fees.ts → sendReminders()",
    newTableHint: "fee_reminders",
    status: "live",
  },

  // ── Communication ──
  {
    id: "COM-SMS-01",
    domain: "communications",
    legacyLabel: "SMS Templates",
    legacyEntryPoint: "Comms > SMS Templates",
    legacyFunctions: ["window.smsTemplates"],
    newModuleHint: "core/comms/service.ts → getTemplates()",
    newTableHint: "message_templates",
    status: "live",
  },
  {
    id: "COM-EMAIL-01",
    domain: "communications",
    legacyLabel: "Email Templates",
    legacyEntryPoint: "Comms > Email Templates",
    legacyFunctions: ["window.emailTemplates"],
    newModuleHint: "core/comms/service.ts → getTemplates()",
    newTableHint: "message_templates",
    status: "live",
  },
  {
    id: "COM-CAMP-01",
    domain: "communications",
    legacyLabel: "Campaigns",
    legacyEntryPoint: "Comms > Campaigns",
    legacyFunctions: ["window.createCampaign()"],
    newModuleHint: "core/comms/service.ts",
    newTableHint: "message_campaigns",
    status: "bridge-required",
  },
  {
    id: "COM-LOG-01",
    domain: "communications",
    legacyLabel: "Message Logs",
    legacyEntryPoint: "Comms > Logs",
    legacyFunctions: ["window.getMessageLogs()"],
    newModuleHint: "core/comms/service.ts",
    newTableHint: "message_logs",
    status: "bridge-required",
  },

  // ── Operations & Tools ──
  {
    id: "OPS-BATCH-01",
    domain: "operations",
    legacyLabel: "Batch Import Wizard",
    legacyEntryPoint: "Import > Batch",
    legacyFunctions: ["window.runImportPipeline()", "importSection"],
    newModuleHint: "src/lib/import-engine/",
    newTableHint: "import_batches",
    status: "live",
  },
  {
    id: "OPS-CLEAN-01",
    domain: "operations",
    legacyLabel: "Data Cleanup",
    legacyEntryPoint: "System > Cleanup",
    legacyFunctions: ["window.cleanupData()"],
    newModuleHint: "src/lib/migration-certification.ts",
    status: "bridge-required",
  },
  {
    id: "OPS-AUDIT-01",
    domain: "operations",
    legacyLabel: "Audit Trail",
    legacyEntryPoint: "System > Audit",
    legacyFunctions: ["window.viewAuditLog()"],
    newModuleHint: "core/audit/service.ts → queryAuditLog()",
    newTableHint: "audit_log",
    status: "live",
  },
  {
    id: "OPS-BACKUP-01",
    domain: "operations",
    legacyLabel: "Backup",
    legacyEntryPoint: "System > Backup",
    legacyFunctions: ["window.backupData()"],
    newModuleHint: "src/pages/Backups.tsx",
    status: "live",
  },
];
