import type { RegistryFieldDefinition } from './types';

export const CANONICAL_FIELDS: RegistryFieldDefinition[] = [
  {
    key: 'registrationNumber',
    label: 'Registration Number',
    aliases: ['reg_no', 'registration_no', 'register_number', 'admission_no', 'admission number', 'admission no'],
    dataType: 'text',
    required: true,
    isKeyField: true,
    isDuplicateKey: true,
    isCustom: false,
    isActive: true,
    scoringWeight: 10,
    group: 'identity',
    dbColumn: 'admission_no',
  },
  {
    key: 'umis',
    label: 'UMIS ID',
    aliases: ['umis', 'umis_id', 'umis id', 'student umis'],
    dataType: 'text',
    required: false,
    isKeyField: true,
    isDuplicateKey: true,
    isCustom: false,
    isActive: true,
    scoringWeight: 5,
    group: 'identity',
    dbColumn: 'umis_id',
  },
  {
    key: 'emis',
    label: 'EMIS ID',
    aliases: ['emis', 'emis_id', 'emis id', 'student emis'],
    dataType: 'text',
    required: false,
    isKeyField: true,
    isDuplicateKey: true,
    isCustom: false,
    isActive: true,
    scoringWeight: 5,
    group: 'identity',
    dbColumn: 'emis_number',
  },
  {
    key: 'studentName',
    label: 'Student Name',
    aliases: ['name', 'student_name', 'studentname', 'full_name', 'full name', 'student full name'],
    dataType: 'text',
    required: true,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 8,
    group: 'personal',
    dbColumn: 'display_name',
  },
  {
    key: 'firstName',
    label: 'First Name',
    aliases: ['first_name', 'firstname', 'given_name', 'student first name'],
    dataType: 'text',
    required: true,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 5,
    group: 'personal',
    dbColumn: 'first_name',
  },
  {
    key: 'lastName',
    label: 'Last Name',
    aliases: ['last_name', 'lastname', 'surname', 'family_name'],
    dataType: 'text',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 3,
    group: 'personal',
    dbColumn: 'last_name',
  },
  {
    key: 'dob',
    label: 'Date of Birth',
    aliases: ['dob', 'birthdate', 'date of birth', 'dateofbirth', 'birth_date'],
    dataType: 'date',
    required: true,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 7,
    group: 'personal',
    dbColumn: 'dob',
  },
  {
    key: 'gender',
    label: 'Gender',
    aliases: ['gender', 'sex'],
    dataType: 'enum',
    required: true,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 5,
    group: 'personal',
    dbColumn: 'gender',
    enumValues: ['Male', 'Female', 'Other', 'Prefer not to say'],
  },
  {
    key: 'bloodGroup',
    label: 'Blood Group',
    aliases: ['blood group', 'bloodgroup', 'blood', 'blood_group'],
    dataType: 'enum',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 2,
    group: 'personal',
    dbColumn: 'blood_group',
    enumValues: ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
  },
  {
    key: 'nationality',
    label: 'Nationality',
    aliases: ['nationality', 'country', 'nation'],
    dataType: 'text',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 2,
    group: 'personal',
    dbColumn: 'nationality',
  },
  {
    key: 'class',
    label: 'Class',
    aliases: ['class', 'grade', 'standard', 'level', 'program', 'semester'],
    dataType: 'text',
    required: true,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 7,
    group: 'academic',
    dbColumn: 'grade',
  },
  {
    key: 'section',
    label: 'Section',
    aliases: ['section', 'division', 'sec', 'batch'],
    dataType: 'text',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 3,
    group: 'academic',
    dbColumn: 'section',
  },
  {
    key: 'rollNumber',
    label: 'Roll Number',
    aliases: ['roll', 'roll_no', 'roll number', 'roll_number'],
    dataType: 'text',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 3,
    group: 'academic',
    dbColumn: 'roll_number',
  },
  {
    key: 'admissionDate',
    label: 'Admission Date',
    aliases: ['admission date', 'admission_date', 'joined_on', 'enrollment date', 'enrollment_date'],
    dataType: 'date',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 4,
    group: 'academic',
    dbColumn: 'joined_on',
  },
  {
    key: 'stream',
    label: 'Stream',
    aliases: ['stream', 'group', 'academic group'],
    dataType: 'text',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 3,
    group: 'academic',
    dbColumn: 'stream',
  },
  {
    key: 'house',
    label: 'House',
    aliases: ['house'],
    dataType: 'text',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 1,
    group: 'academic',
    dbColumn: 'house',
  },
  {
    key: 'academicYear',
    label: 'Academic Year',
    aliases: ['academic year', 'year', 'session', 'academic_year'],
    dataType: 'text',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 3,
    group: 'academic',
    dbColumn: 'academic_year',
  },
  {
    key: 'fatherName',
    label: "Father's Name",
    aliases: ['father name', 'father_name', 'father', 'fathers name'],
    dataType: 'text',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 6,
    group: 'family',
    dbColumn: 'father_name',
  },
  {
    key: 'fatherOccupation',
    label: "Father's Occupation",
    aliases: ['father occupation', 'father_occupation', 'father_job'],
    dataType: 'text',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 2,
    group: 'family',
    dbColumn: 'father_occupation',
  },
  {
    key: 'motherName',
    label: "Mother's Name",
    aliases: ['mother name', 'mother_name', 'mother', 'mothers name'],
    dataType: 'text',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 6,
    group: 'family',
    dbColumn: 'mother_name',
  },
  {
    key: 'motherOccupation',
    label: "Mother's Occupation",
    aliases: ['mother occupation', 'mother_occupation', 'mother_job'],
    dataType: 'text',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 2,
    group: 'family',
    dbColumn: 'mother_occupation',
  },
  {
    key: 'guardianName',
    label: 'Guardian Name',
    aliases: ['guardian name', 'guardian', 'guardian_full_name', 'guardian full name'],
    dataType: 'text',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 4,
    group: 'family',
    dbColumn: 'guardian_name',
  },
  {
    key: 'guardianPhone',
    label: 'Guardian Phone',
    aliases: ['guardian phone', 'parent phone', 'parent mobile', 'guardian_phone', 'parent_phone'],
    dataType: 'phone',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 5,
    group: 'contact',
    dbColumn: 'guardian_phone',
    validationPattern: '^\\+?\\d{7,15}$',
  },
  {
    key: 'guardianEmail',
    label: 'Guardian Email',
    aliases: ['guardian email', 'parent email', 'guardian_email', 'parent_email'],
    dataType: 'email',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 3,
    group: 'contact',
    dbColumn: 'guardian_email',
    validationPattern: '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$',
  },
  {
    key: 'contactNumber',
    label: 'Contact Number',
    aliases: ['contact', 'phone', 'mobile', 'mobile number', 'student mobile', 'contact number', 'phone number'],
    dataType: 'phone',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 5,
    group: 'contact',
    dbColumn: 'phone',
    validationPattern: '^\\+?\\d{7,15}$',
  },
  {
    key: 'alternatePhone',
    label: 'Alternate Phone',
    aliases: ['alternate phone', 'alt phone', 'secondary phone', 'alternate_phone'],
    dataType: 'phone',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 2,
    group: 'contact',
    dbColumn: 'alternate_phone',
    validationPattern: '^\\+?\\d{7,15}$',
  },
  {
    key: 'email',
    label: 'Email',
    aliases: ['email', 'e-mail', 'email address'],
    dataType: 'email',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 4,
    group: 'contact',
    dbColumn: 'email',
    validationPattern: '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$',
  },
  {
    key: 'address',
    label: 'Address',
    aliases: ['address', 'address line', 'mailing address', 'full address'],
    dataType: 'text',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 4,
    group: 'contact',
    dbColumn: 'address',
  },
  {
    key: 'district',
    label: 'District',
    aliases: ['district'],
    dataType: 'text',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 3,
    group: 'contact',
    dbColumn: 'district',
  },
  {
    key: 'community',
    label: 'Community',
    aliases: ['community', 'caste', 'category'],
    dataType: 'text',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 4,
    group: 'identity',
    dbColumn: 'community',
  },
  {
    key: 'firstGraduate',
    label: 'First Graduate',
    aliases: ['first graduate', 'first_graduate', 'first graduate in family'],
    dataType: 'enum',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 3,
    group: 'administrative',
    dbColumn: 'first_graduate',
    enumValues: ['Yes', 'No'],
  },
  {
    key: 'incomeVerified',
    label: 'Income Verified',
    aliases: ['income verified', 'income verification', 'verification status', 'income_verified'],
    dataType: 'enum',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 3,
    group: 'administrative',
    dbColumn: 'income_verified',
    enumValues: ['Verified', 'Pending', 'Not Required'],
  },
  {
    key: 'annualIncome',
    label: 'Annual Income',
    aliases: ['annual income', 'income', 'family income', 'annual_income'],
    dataType: 'text',
    required: false,
    isKeyField: false,
    isDuplicateKey: false,
    isCustom: false,
    isActive: true,
    scoringWeight: 3,
    group: 'family',
    dbColumn: 'annual_income',
  },
];

export const CANONICAL_FIELD_INDEX: Record<string, RegistryFieldDefinition> = {};
for (const field of CANONICAL_FIELDS) {
  CANONICAL_FIELD_INDEX[field.key] = field;
}

export function getFieldByKey(key: string): RegistryFieldDefinition | undefined {
  return CANONICAL_FIELD_INDEX[key];
}

export function getFieldByDbColumn(column: string): RegistryFieldDefinition | undefined {
  return CANONICAL_FIELDS.find((f) => f.dbColumn === column);
}

export function getFieldsByGroup(group: RegistryFieldDefinition['group']): RegistryFieldDefinition[] {
  return CANONICAL_FIELDS.filter((f) => f.group === group);
}

export function getActiveFields(): RegistryFieldDefinition[] {
  return CANONICAL_FIELDS.filter((f) => f.isActive);
}

export function getKeyFields(): RegistryFieldDefinition[] {
  return CANONICAL_FIELDS.filter((f) => f.isKeyField);
}

export function getDuplicateKeyFields(): RegistryFieldDefinition[] {
  return CANONICAL_FIELDS.filter((f) => f.isDuplicateKey);
}

export function getScoringWeights(): { fields: { key: string; weight: number; required: boolean }[] } {
  return {
    fields: CANONICAL_FIELDS.map((f) => ({
      key: f.key,
      weight: f.scoringWeight,
      required: f.required,
    })),
  };
}
