-- Ensure every registry-backed route/system key has at least one permission row
-- so the Permission Matrix can represent the full app shell.
insert into public.permissions (module_key, action, label) values
  ('accounts', 'view', 'View Accounts'),
  ('activity-log', 'view', 'View Activity Log'),
  ('administration', 'view', 'View Administration'),
  ('admissions', 'view', 'View Admissions'),
  ('ai', 'view', 'View AI Assistant'),
  ('alumni', 'view', 'View Alumni'),
  ('assignments', 'view', 'View Assignments'),
  ('attendance', 'view', 'View Attendance'),
  ('automation', 'view', 'View Automation'),
  ('backups', 'view', 'View Backups'),
  ('certificates', 'view', 'View Certificates'),
  ('chat', 'view', 'View Chat'),
  ('class-mgmt', 'view', 'View Class Management'),
  ('class-wall', 'view', 'View Class Wall'),
  ('collegeInfo', 'view', 'View Institute Identity'),
  ('communication', 'view', 'View Communication'),
  ('courseInfo', 'view', 'View Course Information'),
  ('discipline', 'view', 'View Discipline'),
  ('documents', 'view', 'View Documents'),
  ('events', 'view', 'View Events'),
  ('exams', 'view', 'View Exams'),
  ('fees', 'view', 'View Fees'),
  ('grievances', 'view', 'View Grievances'),
  ('health', 'view', 'View Health'),
  ('holidays', 'view', 'View Holidays'),
  ('homework', 'view', 'View Homework'),
  ('hostel', 'view', 'View Hostel'),
  ('hr', 'view', 'View HR & Payroll'),
  ('inventory', 'view', 'View Inventory'),
  ('leave-master', 'view', 'View Leave Master'),
  ('lessons', 'view', 'View Lessons'),
  ('library', 'view', 'View Library'),
  ('media', 'view', 'View Media'),
  ('migration', 'view', 'View Migration Center'),
  ('notice-board', 'view', 'View Notice Board'),
  ('notifications', 'view', 'View Notifications'),
  ('online-exams', 'view', 'View Online Exams'),
  ('parents', 'view', 'View Parent Portal'),
  ('payroll', 'view', 'View Payroll'),
  ('people', 'view', 'View People'),
  ('placement', 'view', 'View Placement'),
  ('quiz', 'view', 'View Quiz'),
  ('reception', 'view', 'View Reception'),
  ('reports', 'view', 'View Reports'),
  ('reportsAnalytics', 'view', 'View Reports Analytics'),
  ('roles', 'view', 'View Permission Matrix'),
  ('scholarships', 'view', 'View Scholarships'),
  ('security', 'view', 'View Security & Audit'),
  ('settings', 'view', 'View Settings'),
  ('settingsBackup', 'view', 'View Settings Backup'),
  ('students', 'view', 'View Students'),
  ('subjects', 'view', 'View Subjects'),
  ('system', 'view', 'View System'),
  ('taskManagement', 'view', 'View Task Management'),
  ('tasks', 'view', 'View Tasks'),
  ('telephone', 'view', 'View Telephone'),
  ('timetable', 'view', 'View Timetable'),
  ('transport', 'view', 'View Transport'),
  ('userManagement', 'view', 'View User Management'),
  ('videoRooms', 'view', 'View Video Rooms')
on conflict do nothing;

insert into public.role_permissions (role, permission_id, level)
select
  rr.app_role,
  p.id,
  public.default_role_permission_level(rr.app_role, p.module_key)
from public.permissions p
cross join unnest(enum_range(null::public.app_role)) as rr(app_role)
where p.module_key in (
  'accounts',
  'activity-log',
  'administration',
  'admissions',
  'ai',
  'alumni',
  'assignments',
  'attendance',
  'automation',
  'backups',
  'certificates',
  'chat',
  'class-mgmt',
  'class-wall',
  'collegeInfo',
  'communication',
  'courseInfo',
  'discipline',
  'documents',
  'events',
  'exams',
  'fees',
  'grievances',
  'health',
  'holidays',
  'homework',
  'hostel',
  'hr',
  'inventory',
  'leave-master',
  'lessons',
  'library',
  'media',
  'migration',
  'notice-board',
  'notifications',
  'online-exams',
  'parents',
  'payroll',
  'people',
  'placement',
  'quiz',
  'reception',
  'reports',
  'reportsAnalytics',
  'roles',
  'scholarships',
  'security',
  'settings',
  'settingsBackup',
  'students',
  'subjects',
  'system',
  'taskManagement',
  'tasks',
  'telephone',
  'timetable',
  'transport',
  'userManagement',
  'videoRooms'
)
on conflict (role, permission_id) do nothing;
