// This file is automatically generated. Do not edit it directly.
import "@/lib/runtime-storage";
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

type StorageLike = Pick<Storage, "getItem" | "setItem" | "removeItem" | "clear" | "key"> & {
  readonly length: number;
};

type SupabaseEnv = {
  VITE_SUPABASE_URL?: string;
  VITE_SUPABASE_PUBLISHABLE_KEY?: string;
};

const readEnv = (): SupabaseEnv => {
  const viteEnv = (import.meta as ImportMeta & { env?: SupabaseEnv }).env;
  const processEnv = typeof process !== "undefined" ? process.env : undefined;
  return {
    VITE_SUPABASE_URL: viteEnv?.VITE_SUPABASE_URL ?? processEnv?.VITE_SUPABASE_URL,
    VITE_SUPABASE_PUBLISHABLE_KEY: viteEnv?.VITE_SUPABASE_PUBLISHABLE_KEY ?? processEnv?.VITE_SUPABASE_PUBLISHABLE_KEY,
  };
};

const createMemoryStorage = (): StorageLike => {
  const store = new Map<string, string>();
  return {
    get length() {
      return store.size;
    },
    clear() {
      store.clear();
    },
    getItem(key) {
      return store.has(key) ? store.get(key)! : null;
    },
    key(index) {
      return Array.from(store.keys())[index] ?? null;
    },
    removeItem(key) {
      store.delete(key);
    },
    setItem(key, value) {
      store.set(key, String(value));
    },
  };
};

const getAuthStorage = (): StorageLike => {
  try {
    return window.localStorage as StorageLike;
  } catch {
    return createMemoryStorage();
  }
};

const createNoopBuilder = () => {
  const response = Promise.resolve({ data: null, error: null });
  const builder = new Proxy(function noopBuilder() {}, {
    get(_target, prop) {
      if (prop === "then") return response.then.bind(response);
      if (prop === "catch") return response.catch.bind(response);
      if (prop === "finally") return response.finally.bind(response);
      if (prop === Symbol.toPrimitive) return () => "";
      return () => builder;
    },
    apply() {
      return builder;
    },
  });

  return builder;
};

const createNoopAuth = () => ({
  async getSession() {
    return { data: { session: null }, error: null };
  },
  async getUser() {
    return { data: { user: null }, error: null };
  },
  async signInWithPassword() {
    return { data: { user: null, session: null }, error: null };
  },
  async signInWithOtp() {
    return { data: { user: null, session: null }, error: null };
  },
  async signUp() {
    return { data: { user: null, session: null }, error: null };
  },
  async signOut() {
    return { error: null };
  },
  async updateUser() {
    return { data: { user: null }, error: null };
  },
  async refreshSession() {
    return { data: { session: null }, error: null };
  },
  async setSession() {
    return { data: { session: null }, error: null };
  },
  onAuthStateChange() {
    return { data: { subscription: { unsubscribe() {} } }, error: null };
  },
});

const createNoopSupabaseClient = () => {
  const builder = createNoopBuilder();
  const auth = createNoopAuth();

  return new Proxy(function noopClient() {}, {
    get(_target, prop) {
      if (prop === "auth") return auth;
      if (prop === "from") return () => builder;
      if (prop === "rpc") return () => builder;
      if (prop === "storage") return getAuthStorage();
      if (prop === "channel") {
        return () => ({
          subscribe: async () => ({ data: null, error: null }),
          unsubscribe() {},
        });
      }
      if (prop === "removeChannel") return async () => ({ data: null, error: null });
      if (prop === "getChannels") return () => [];
      if (prop === Symbol.toPrimitive) return () => "";
      return () => builder;
    },
    apply() {
      return builder;
    },
  });
};

const { VITE_SUPABASE_URL: SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY: SUPABASE_PUBLISHABLE_KEY } = readEnv();
const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = hasSupabaseConfig
  ? createClient<Database>(SUPABASE_URL as string, SUPABASE_PUBLISHABLE_KEY as string, {
      auth: {
        storage: getAuthStorage(),
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : (createNoopSupabaseClient() as unknown as ReturnType<typeof createClient<Database>>);
